language: python
python:
- '2.7'
env:
  global:
  - GAE_DIR=/tmp/gae
  - EMAIL=appsamblea@gmail.com
  - secure: NV0YZr03IcXAPhVNjfNptYlwl74TEMHn+rkvwB1BGKXffDOya5HnXU5fVWv2NIHMQIRLslolpfldTxvhB79IDTGs06BDjpRu7rAWi6uPRlQkL8P7q+2L5p5ZoMV2Zf5UTCBv9xdkngLh85S8iWfcnxyhFi07DZotJXI6nmZ1pW6waO8GgEw1AVt/HcR3oYKCX1qnbstewe/BIiBNDlr52JEpzaxoNEqn5ku6ZAsouMNKvKc/8Itd+mA6cWKKPtLr9hWreEXaYQyO/2qWPdviiq4o/6ZmxJ2NthzhOKYycsaQLVlFv4ErBbSPIkjRMrV/qqATv34O7bsRzERV6o+nvw==
  - secure: gO1BzOxiQRc1kh+n84XcuTWw+rKLhINTqoSAgt5rXJGXCThxh+e4FwBkGLUhR6mC96U/rBGGKCCwvb7ZvOvs6acUFLty5ICfq755hm+mXXqyKKGKFTEtSUGH0qsXGeLqf/EeKLCQpZpusaCLZF1Rt9KB2ZFCq2jYbVAlWkrDeSI=
before_install:
- test -e $GAE_DIR ||  (mkdir -p $GAE_DIR &&  wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.15.zip -q -O /tmp/gae.zip && unzip -q /tmp/gae.zip -d $GAE_DIR)
- rm $GAE_DIR/google_appengine/lib/fancy_urllib/__init__.py
- cp $GAE_DIR/google_appengine/lib/fancy_urllib/fancy_urllib/__init__.py $GAE_DIR/google_appengine/lib/fancy_urllib/__init__.py
install:
- pip install -r requirements.txt
before_script:
- export PYTHONPATH="$PYTHONPATH:/tmp/gae/google_appengine/:/tmp/gae/google_appengine/lib/:/tmp/gae/google_appengine/lib/yaml/:/tmp/gae/google_appengine/lib/yaml-3.10/"
script:
- python manage.py test
after_success: "./after_success.sh"
