from main_appsamblea.models.greetings import *
from main_appsamblea.models.usuario import Usuario
from main_appsamblea.models.organizacion import Organizacion
from main_appsamblea.models.asamblea import Asamblea
from main_appsamblea.models.participa import Participa
from main_appsamblea.models.acta import Acta
from main_appsamblea.models.documento import Documento
from main_appsamblea.models.grupo import Grupo
from main_appsamblea.models.mensaje import Mensaje
from main_appsamblea.models.turno_palabra import Turno_palabra
from main_appsamblea.models.punto_orden import Punto_orden_dia
from main_appsamblea.models.votacion import Votacion
from main_appsamblea.models.votacion_opcion import Votacion_opcion
from main_appsamblea.models.responsabilidad import Responsabilidad
